version: '3.1'
networks:
  default:
    external:
      name: colin
services:
  cassandra1:
    image: cassandra:latest
    restart: always
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - /Users/colin/Applications/docker-apps/data/cassandra1:/var/lib/cassandra
    environment:
      - CASSANDRA_DC=datacenter1
