version: '3.1'
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: colin
      POSTGRES_PASSWORD: hope
    volumes:
      - /Users/colin/Applications/docker-apps/data/postgres:/var/lib/postgresql/data

  cassandra1:
    image: cassandra:latest
    restart: always
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - /Users/colin/Applications/docker-apps/data/cassandra1:/var/lib/cassandra
    environment:
      - CASSANDRA_DC=datacenter1
