networks:
  default:
    external:
      name: colin

version: "3.2"
services:
  # zookeeper 服务
  zookeeper-service:
    image: 'bitnami/zookeeper:latest'
    restart: always
    expose:
      - 2181
      - 2888
      - 3888
      - 8080
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka 服务
  kafka-service:
    image: 'bitnami/kafka:latest'
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper-service
    links:
      - zookeeper-service:zookeeper-service
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-service:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_BROKER_ID=1001
      - KAFKA_CFG_RESERVED_BROKER_MAX_ID=10000
      - KAFKA_HEAP_OPTS=-Xmx256M -Xms256M
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
