networks:
  default:
    name: freeriver
    external: true

services:
  akhq:
      # build:
      #   context: .
      image: tchiotludo/akhq
      restart: unless-stopped
      ports: 
        - 9000:8080
      environment:
        AKHQ_CONFIGURATION: |
          akhq:
            connections:
              kafka-server:
                properties:
                  # current not works, should use host network on linux as mac or windows docker don't supported the host network
                  bootstrap.servers: "host.docker.internal:9092"  