networks:
  default:
    external:
      name: freeriver

version: "3.3"
services:
  akhq:
      # build:
      #   context: .
      image: tchiotludo/akhq
      restart: unless-stopped
      ports: 
        - 9000:8080
      links:
        - kafka-server
      environment:
        AKHQ_CONFIGURATION: |
          akhq:
            connections:
              kafka-server:
                properties:
                  bootstrap.servers: "kafka-server:9092"