version: '3.1'
networks:
  default:
    external:
      name: colin
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: colin
      POSTGRES_PASSWORD: hope
    volumes:
      - /Users/colin/Applications/docker-apps/data/postgres:/var/lib/postgresql/data
