version: '3.1'
networks:
  default:
    external:
      name: colin
services:
  redis:
    image: bitnami/redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /Users/colin/Applications/docker-apps/data/redis-persistence:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
