networks:
  default:
    external:
      name: colin

version: "3.2"
services:
  zookeeper-service:
    image: 'bitnami/zookeeper:latest'
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
    expose:
      - 2181
      - 2888
      - 3888
      - 8080
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes